<?php
// This file generated by Propel 1.6.9 convert-conf target
return array (
  'BasePbi' => 'Scrumboard/om/BasePbi.php',
  'BasePbiPeer' => 'Scrumboard/om/BasePbiPeer.php',
  'BasePbiQuery' => 'Scrumboard/om/BasePbiQuery.php',
  'BaseRouter' => 'Scrumboard/om/BaseRouter.php',
  'BaseRouterPeer' => 'Scrumboard/om/BaseRouterPeer.php',
  'BaseRouterQuery' => 'Scrumboard/om/BaseRouterQuery.php',
  'Pbi' => 'Scrumboard/Pbi.php',
  'PbiPeer' => 'Scrumboard/PbiPeer.php',
  'PbiQuery' => 'Scrumboard/PbiQuery.php',
  'PbiTableMap' => 'Scrumboard/map/PbiTableMap.php',
  'Router' => 'Scrumboard/Router.php',
  'RouterPeer' => 'Scrumboard/RouterPeer.php',
  'RouterQuery' => 'Scrumboard/RouterQuery.php',
  'RouterTableMap' => 'Scrumboard/map/RouterTableMap.php',
);