<?php
// This file generated by Propel 1.6.9 convert-conf target
// from XML runtime conf file /var/www/scrumboard/Helix/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'scrumboard' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:dbname=scrumboard;host=localhost',
        'user' => 'scrumboard',
        'password' => 'scrumboard',
        'options' => 
        array (
          'ATTR_PERSISTENT' => 
          array (
            'value' => false,
          ),
          'ATTR_EMULATE_PREPARES' => 
          array (
            'value' => true,
          ),
        ),
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'scrumboard',
  ),
  'generator_version' => '1.6.9',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-conf.php');
return $conf;